# Generated by Django 4.0.1 on 2022-03-08 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('purchase_date', models.DateField()),
                ('po', models.CharField(max_length=100)),
                ('merchant_material_code', models.CharField(blank=True, max_length=100, null=True)),
                ('merchant_unit_measurement', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.material')),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.merchant')),
            ],
        ),
    ]
