# Generated by Django 3.1.7 on 2022-02-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('download_url', models.TextField()),
                ('drive_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_documents',
            field=models.ManyToManyField(to='dashboard.OrderDocument'),
        ),
    ]
