# Generated by Django 4.0.1 on 2022-03-14 20:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_order_order_creator_alter_order_order_materials_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchantmaterials',
            old_name='material',
            new_name='material_id',
        ),
        migrations.RemoveField(
            model_name='material',
            name='units',
        ),
        migrations.RemoveField(
            model_name='merchantmaterials',
            name='po',
        ),
        migrations.RemoveField(
            model_name='merchantmaterials',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='merchant',
            name='contact_role',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='merchant_code',
            field=models.IntegerField(default=4, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MaterialsOnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(unique=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.merchantmaterials')),
                ('po_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.process')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_available', models.IntegerField()),
                ('unit_reserved_for_orders', models.IntegerField()),
                ('unit_defective', models.IntegerField()),
                ('total_units_on_order', models.IntegerField()),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.material')),
            ],
        ),
    ]
