# Generated by Django 4.0.1 on 2022-02-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_order_id_alter_order_order_documents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_location', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderdocument',
            name='download_url',
        ),
        migrations.RemoveField(
            model_name='orderdocument',
            name='drive_id',
        ),
        migrations.AddField(
            model_name='orderdocument',
            name='file_location',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_images',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.OrderImage'),
        ),
    ]
