# Generated by Django 4.0.1 on 2022-03-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_order_order_creator_alter_order_order_materials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_new_order_emails', models.BooleanField(default=True)),
            ],
        ),
    ]
