# Generated by Django 4.0.1 on 2022-03-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_applicationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsettings',
            name='send_new_user_emails',
            field=models.BooleanField(default=True),
        ),
    ]
