# Generated by Django 4.0.1 on 2022-03-15 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('dashboard', '0004_rename_material_merchantmaterials_material_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialinventory',
            name='material_id',
        ),
        migrations.RemoveField(
            model_name='materialsonorder',
            name='material_id',
        ),
        migrations.RemoveField(
            model_name='materialsonorder',
            name='po_number',
        ),
        migrations.RemoveField(
            model_name='merchantmaterials',
            name='material_id',
        ),
        migrations.RemoveField(
            model_name='merchantmaterials',
            name='merchant_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_materials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.material'),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='MaterialInventory',
        ),
        migrations.DeleteModel(
            name='MaterialsOnOrder',
        ),
        migrations.DeleteModel(
            name='Merchant',
        ),
        migrations.DeleteModel(
            name='MerchantMaterials',
        ),
    ]
