# Generated by Django 4.0.1 on 2022-02-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderimage',
            name='alt_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderimage',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderimage',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
