# Generated by Django 4.0.1 on 2022-04-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_applicationsettings_send_new_user_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
