# Generated by Django 4.0.1 on 2022-03-24 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_materialinventory_archive_and_more'),
        ('dashboard', '0005_remove_materialinventory_material_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_materials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.materialinventory'),
        ),
    ]
