# Generated by Django 4.0.1 on 2022-04-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_process_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchantmaterials',
            old_name='merchant_id',
            new_name='merchant',
        ),
    ]
