# Generated by Django 4.0.1 on 2022-04-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_merchant_id_merchantmaterials_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantmaterials',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
