# Generated by Django 4.0.1 on 2022-04-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_merchantmaterials_po_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_materials',
        ),
        migrations.AddField(
            model_name='order',
            name='order_materials',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.Material'),
        ),
    ]
