# Generated by Django 4.0.1 on 2022-04-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_order_order_materials_order_order_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_materials',
            field=models.ManyToManyField(blank=True, to='dashboard.Material'),
        ),
    ]
