# Generated by Django 4.0.1 on 2022-03-15 14:44

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('material_code', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_measurement', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_code', models.IntegerField(unique=True)),
                ('company_name', models.CharField(max_length=75)),
                ('contact_name', models.CharField(max_length=75)),
                ('contact_role', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('merchant_material_code', models.CharField(blank=True, max_length=100, null=True)),
                ('merchant_unit_measurement', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=True)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.material')),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialsOnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('order_date', models.DateField(auto_now_add=True)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.merchantmaterials')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_available', models.IntegerField()),
                ('units_reserved_for_orders', models.IntegerField()),
                ('units_defective', models.IntegerField()),
                ('total_units_on_order', models.IntegerField()),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.material')),
            ],
        ),
    ]
