# Generated by Django 4.0.1 on 2022-03-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='status',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='status',
        ),
        migrations.RemoveField(
            model_name='merchantmaterials',
            name='status',
        ),
        migrations.AddField(
            model_name='material',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialinventory',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialsonorder',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchantmaterials',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchantmaterials',
            name='avg_order_processing_time',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
