# Generated by Django 4.0.1 on 2022-03-24 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_order_order_materials'),
        ('inventory', '0004_remove_materialinventory_archive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialinventory',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialinventory',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='materialinventory',
            name='material_code',
            field=models.CharField(default=2, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialinventory',
            name='name',
            field=models.CharField(default=3, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialinventory',
            name='unit_measurement',
            field=models.CharField(default=4, max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='materialsonorder',
            name='MaterialsOnOrder',
        ),
        migrations.AddField(
            model_name='materialsonorder',
            name='MaterialsOnOrder',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='inventory.merchantmaterials'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='merchantmaterials',
            name='material_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.materialinventory'),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
