# Generated by Django 4.0.1 on 2022-03-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_unit_measurement_materialinventory_units_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='merchant_code',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
